plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

// retirar depois de implementado
bootJar {
    enabled = false
}

jar {
    enabled = true
}


description = 'Microsserviço de escrita — recebe intenções de trade, valida e persiste em PostgreSQL sob ACID, publica TradeExecutedEvent no Kafka'

repositories {
    mavenCentral()
    // Necessário para kafka-avro-serializer / kafka-schema-registry-client
    maven {
        url = uri ("https://packages.confluent.io/maven/") }
}

ext {
    confluentVersion = '7.9.0' // confirme a versão compatível com a versão do Kafka usada no docker-compose
}

dependencies {
    implementation project(':clearing-domain')
    implementation project(':clearing-contracts')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation "io.confluent:kafka-avro-serializer:${confluentVersion}"
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}
