spring:
  application:
    name: trade-query-service

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: trade-query-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

clearing:
  kafka:
    topic:
      trade-executed: market.trades.v1

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, info
